### ISSUE TITLE
Cannot read property 'cache' of undefined

### ISSUE THREAD

**Issue by mohalepooja** [5up-okamura/react-native-draggable-gridview#3]
Hi Team,

I was trying to use this liberary in my project. I am able to successfully install it but when I try to use it in my file I get following error,
"TypeError \node_modules\\react-native-draggable-gridview\src\\index.tsx: cannot read property 'cache' of undefined".

This error goes when I comment out the line from babel.config.js under node_modules file, It works.

module.exports = function(api) {
  // api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};

But this should not be the fix for my project. Could you provide any solution for the issue?

**Comment by 5up-okamura** [comment]
@lemankk Thank you for the solution.
